### ISSUE TITLE
I get an error trying to install

### ISSUE THREAD

**Issue by pwall2222** [JezerM/web-greeter#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/pyrcc5", line 33, in <module>
    sys.exit(load_entry_point('PyQt5==5.15.4', 'console_scripts', 'pyrcc5')())
  File "/usr/local/bin/pyrcc5", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/PyQt5-5.15.4-py3.9-linux-x86_64.egg/PyQt5/pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: /usr/local/lib/python3.9/dist-packages/PyQt5-5.15.4-py3.9-linux-x86_64.egg/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```
When trying to `sudo make install`

**Comment by JezerM** [comment]
Seems you don't have the latest PyQt5 release. Install it with pip `pip install PyQt5`

**Comment by pwall2222** [comment]
It was my fault, cause i installed it via apt and the version seemed uncompatible so uninstalling the apt version and using the pip version resolved that issue.
