### ISSUE TITLE
I get an error trying to open the greeter

### ISSUE THREAD

**Issue by pwall2222** [JezerM/web-greeter#2]
```
> web-greeter  --debug
2021-06-24 21:11:02 [ DEBUG ] objects - objects.py:124 : _setup_logger | Logger is ready.
2021-06-24 21:11:02 [ DEBUG ] app - app.py:57 : _wh_load_config | Try load config using key: WebGreeter
2021-06-24 21:11:02 [ DEBUG ] window - window.py:81 : _initialize | Initializing Main Window
2021-06-24 21:11:02 [ DEBUG ] globals - globals.py:96 : get_and_apply_user_config | Aplying config

DevTools listening on ws://127.0.0.1:12345/devtools/browser/aab56a36-613d-4521-b2a3-3588636f496b
2021-06-24 21:11:02 [ DEBUG ] globals - globals.py:66 : __init__ | Web Greeter started.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/web-greeter/__main__.py", line 200, in <module>
  File "/usr/bin/web-greeter/globals.py", line 67, in __init__
  File "/usr/bin/web-greeter/bridge/Greeter.py", line 120, in __init__
gi.repository.GLib.Error: lightdm_greeter_error: Unable to determine socket to daemon (1)
```

**Comment by pwall2222** [comment]
Nevermind, it was an issue of following the guide and adding `X-LightDM-Allow-Greeter=true` to the xsession.
