### ISSUE TITLE
No module named 'resources'

### ISSUE THREAD

**Issue by jackzzs** [JezerM/web-greeter#21]
## Environment
- OS: Ubuntu 20.04
- web-greeter version: 3.1.1

## Bug description
web-greeter exit with import error when excuted (by root or lightdm).

## Steps to reproduce
```console
$ sudo su
# web-greeter
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/web-greeter/__main__.py", line 98, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/bin/web-greeter/browser/browser.py", line 56, in <module>
ModuleNotFoundError: No module named 'resources'
```

## Expected behavior
~

## **Screenshots**
```console
$ sudo su
# pip list
Package                Version
---------------------- --------------------
apturl                 0.5.2
blinker                1.4
Brlapi                 0.7.0
certifi                2019.11.28
chardet                3.0.4
chrome-gnome-shell     0.0.0
Click                  7.0
colorama               0.4.3
cryptography           2.8
cupshelpers            1.0
cx-Freeze              6.8.2
dbus-python            1.2.16
defer                  1.0.6
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
httplib2               0.14.0
idna                   2.8
importlib-metadata     4.8.2
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
louis                  3.12.0
macaroonbakery         1.3.1
netifaces              0.10.4
oauthlib               3.1.0
olefile                0.46
pexpect                4.6.0
Pillow                 7.0.0
pip                    20.0.2
protobuf               3.6.1
pycairo                1.16.2
pycups                 1.9.73
Pygments               2.3.1
PyGObject              3.36.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
PyQt5                  5.15.6
PyQt5-Qt5              5.15.2
PyQt5-sip              12.9.0
PyQtWebEngine          5.15.5
PyQtWebEngine-Qt5      5.15.2
pyRFC3339              1.1
python-apt             2.0.0+ubuntu0.20.4.6
python-dateutil        2.7.3
python-debian          0.1.36ubuntu1
python-xlib            0.31
pytz                   2019.3
pyxdg                  0.26
PyYAML                 5.3.1
reportlab              3.5.34
requests               2.22.0
requests-unixsocket    0.2.0
ruamel.yaml            0.17.17
ruamel.yaml.clib       0.2.6
SecretStorage          2.3.1
setuptools             45.2.0
simplejson             3.16.0
sip                    4.19.21
six                    1.14.0
ssh-import-id          5.10
systemd-python         234
ubuntu-advantage-tools 27.4
ubuntu-drivers-common  0.0.0
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
wadllib                1.3.3
wheel                  0.34.2
xkit                   0.0.0
zipp                   3.6.0
```

**Comment by JezerM** [comment]
How did you build web-greeter? Seems like pyrcc didn't do its job, and so `resources` module is unavailable.
